# spawn-cap: maximum number of entities per chunk before breeding is disabled
# entity-list: mobs that are counted in a chunk's total count
# breeding-fail-msg: message sent to the player when breeding is disabled due to chunk capacity

spawn-cap: 100
breeding-fail-msg: "Das Tier schaut nervös zu allen Seiten .. Es ist zu überfüllt um hier zu Züchten!"

entity-list:
  - pig
  - cow
  - chicken
  - sheep

#use-individual-cap: specify whether you wish to use the individual entity list and individual entity limit checking
use-individual-cap: true
#entity-list-individual: (entitytype, spawnlimit)
entity-list-individual:
  - pig, 5
  - cow, 5
  - chicken, 5
  - sheep, 5