# spawn-cap: maximum number of entities per chunk before breeding is disabled
# entity-list: mobs that are counted in a chunk's total count
spawn-cap: 100
entity-list:
  - pig
  - cow
  - chicken
  - sheep
